### ISSUE TITLE
Fix bootstrap

### ISSUE THREAD

**Issue by kventos** [sanekas/fair-elections#7]
1. Need to change bootstrap import by http on local path
2. Tune display of pictures on different screen sizes.

**Comment by Gumil9** [comment]
1. Remove pictures
2. Fix displaying on mobile screens (increse active elements size)

**Comment by Gumil9** [comment]
Также в консоли показывается ошибка:
`Uncaught Error: Bootstrap's JavaScript requires jQuery(…)`

**Comment by Gumil9** [comment]
Использовать тег <br> для увеличения расстояния между кнопками (<div>) очень плохо. Намного лучше задать этот интервал стилями. Вообще тег <br> предназначен оформления текста.

**Comment by Gumil9** [comment]
Все align="center" лучше вынести в стили

**Comment by kventos** [comment]
не знаю как задать интервал между кнопками в стиле. Если знаешь, вставь, а я пока оставлю <br/>

**Comment by Gumil9** [comment]
Можно использовать свойство `margin`
